request:
  url:
    routes: https://services-api.ryanair.com/views/locate/3/routes
#               https://services-api.ryanair.com/timtbl/3/schedules/{departure}/{arrival}/years/{year}/months/{month}
    schedulers: https://services-api.ryanair.com/timtbl/3/schedules/%s/%s/years/%d/months/%d
